first pass at tfvars for simpler code base
broadinstitute/terraform-jade pull request #103
Opened 2020-11-05 15:57 UTC by smark88

- switched to tfvars
- terrform 0.13.5 upgrade
- google provider update
- actions update
- updated readme.md

2020-11-05 16:13 UTC, fboulnois requested changes
I like this new setup, it's a lot simpler. A few suggestions:

2020-11-05 16:13 UTC, fboulnois commented on README.md
> +./terraform.sh init -backend-config=bucket=<googe_project>
```suggestion
./terraform.sh init -backend-config=bucket=<google_project>
```

2020-11-05 16:13 UTC, fboulnois commented on README.md
> +- `<googe_project>` is for the statefile its the name of the google project typically
```suggestion
- `<google_project>` is for the statefile its the name of the google project typically
```

2020-11-05 16:13 UTC, fboulnois commented on .github/workflows/terraformPrPlan.yml
> +          echo "VAULT_TOKEN=$(echo ${VAULT_TOKEN})" >> $GITHUB_ENV
If I understand correctly, you're pushing everything into an environment file called `${GITHUB_ENV}`? Also, any concerns about leaking credentials using `echo`? If you set a mask on `${VAULT_TOKEN}` I think you can simplify this to `echo "VAULT_TOKEN=${VAULT_TOKEN}"`

2020-11-05 16:16 UTC, smark88 commented on .github/workflows/terraformPrPlan.yml
> +          echo "VAULT_TOKEN=$(echo ${VAULT_TOKEN})" >> $GITHUB_ENV
This is the new way to set env vars.

2020-11-05 16:21 UTC, smark88 commented on .github/workflows/terraformPrPlan.yml
> +          echo "VAULT_TOKEN=$(echo ${VAULT_TOKEN})" >> $GITHUB_ENV
also this did not work `echo "VAULT_TOKEN=${VAULT_TOKEN}" >> ${GITHUB_ENV}`

2020-11-05 17:40 UTC, rhiananthony requested changes

2020-11-05 17:40 UTC, rhiananthony commented on .github/workflows/terraformPrPlan.yml
> +      - name: install terrform
nit: typo

2020-11-05 17:40 UTC, rhiananthony commented on datarepo/terraform.sh
>  #DOCKER_IMAGE='broadinstitute/terraform:latest'
Should you just remove the comment? Seems like it isn't necessary/ might be confusing.

2020-11-05 17:40 UTC, rhiananthony commented on datarepo/variables.tf
>    description = "number of kubernetes nodes depends on if region is us-central1 1 will deploy 3 and us-central1-a 3 will deploy 3"
This description is confusing.

2020-11-05 18:08 UTC, smark88 commented on datarepo/terraform.sh
>  #DOCKER_IMAGE='broadinstitute/terraform:latest'
yeah thats carry over form forever ago

2020-11-05 20:25 UTC, smark88 commented
Could use some thumbs. If it all looks good.

2020-11-06 16:19 UTC, rhiananthony approved these changes
LGTM

2020-11-06 16:41 UTC, merged